# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.9.0.schema.json
PackageIdentifier: NotNull92.Hera
PackageVersion: 0.8.0
Platform:
- Windows.Desktop
MinimumOSVersion: 10.0.0.0
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: hera.exe
  PortableCommandAlias: hera
ReleaseDate: 2026-07-13
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/NotNull92/hera-agent-godot/releases/download/v0.8.0/hera-windows-amd64.zip
  InstallerSha256: F759A0306EF04AFD5D449C704672376093586D3F4DE874B5BBCDA8FB99DABD4F
- Architecture: arm64
  InstallerUrl: https://github.com/NotNull92/hera-agent-godot/releases/download/v0.8.0/hera-windows-arm64.zip
  InstallerSha256: 3E470C99AEE19EF26D61DAC4554F77CAE56AE3C77D32263EDA4C52B463FC831A
ManifestType: installer
ManifestVersion: 1.9.0
